# fly.toml --- pg-threads-bot
app = "pg-threads-bot"
primary_region = "sjc"

[env]
EXPIRY_WARN_DAYS    = "7"
POST_INTERVAL_HOURS = "1"          # index.js reads this
# THREADS_ACCESS_TOKEN will be set as a secret, not checked-in

[[vm]]
  cpu_kind = "shared"
  memory   = "256mb"               # plenty for a one-shot job